### ISSUE TITLE
Looks like a great package, if only I could use it ...

### ISSUE THREAD

**Issue by tedmoorman** [seunglee98/fedmatch#3]
I'll just say that this package looks like it's exactly what I need. If only we had an RStudio version installed that would allow us to select R v4.0 or higher. Hopefully that changes soon.

As a result, I'll be trying out ```fastLink``` and ```diyar```.

 Cheers.

**Comment by tedmoorman** [comment]
I was able to download the development version of the package. I changed the ```DESCRIPTION``` file to allow for ```Depends:
    R (>= 3.5.3)```.  So far, so good. I'm wondering if the dependency on the later version of R is necessary.

**Comment by c0webster** [comment]
Hi Ted, thanks for checking this! I've received this request from someone else recently, so I will look into it. Thanks for the positive data point of 3.5.3.

**Comment by c0webster** [comment]
This has been updated in the current development version - please feel free to give it a try.
